FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./App ./App

CMD ["uvicorn", "App.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
